[http]
listen = "0.0.0.0:3000"
internal_url = "http://127.0.0.1:3000/"
external_url = "http://10.1.1.10:3000/"

[mpd]
socket = "tmp/mpd/mpd.sock"

[storage]
database = "hailsplay.db"
archive = "tmp/archive"
working = "tmp/working"
